//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _100 {
            get {
                object obj = ResourceManager.GetObject("_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _120 {
            get {
                object obj = ResourceManager.GetObject("_120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20 {
            get {
                object obj = ResourceManager.GetObject("_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _30 {
            get {
                object obj = ResourceManager.GetObject("_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _40 {
            get {
                object obj = ResourceManager.GetObject("_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _50 {
            get {
                object obj = ResourceManager.GetObject("_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _60s {
            get {
                object obj = ResourceManager.GetObject("_60s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _70 {
            get {
                object obj = ResourceManager.GetObject("_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _80 {
            get {
                object obj = ResourceManager.GetObject("_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _90 {
            get {
                object obj = ResourceManager.GetObject("_90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background_app2 {
            get {
                object obj = ResourceManager.GetObject("background app2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background_app3 {
            get {
                object obj = ResourceManager.GetObject("background app3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background_app4 {
            get {
                object obj = ResourceManager.GetObject("background app4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background_app45 {
            get {
                object obj = ResourceManager.GetObject("background app45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///10
        ///10
        ///7
        ///7
        ///6
        ///3
        ///8
        ///5
        ///6
        ///12
        ///10
        ///6
        ///12
        ///8
        ///7
        ///5
        ///8
        ///8
        ///3
        ///10
        ///6
        ///10
        ///6
        ///3
        ///5
        ///6
        ///3
        ///8
        ///7
        ///7
        ///3
        ///6
        ///3
        ///10
        ///3
        ///12
        ///5
        ///3
        ///9
        ///6
        ///5
        ///7
        ///9
        ///5
        ///10
        ///6
        ///9
        ///10
        ///7
        ///7
        ///3
        ///6
        ///5
        ///12
        ///7
        ///3
        ///12
        ///5
        ///12
        ///7
        ///3
        ///5
        ///8
        ///8
        ///7
        ///5
        ///7
        ///8
        ///3
        ///8
        ///12
        ///7
        ///2
        ///8
        ///12
        ///2
        ///3
        ///8
        ///5
        ///3
        ///3
        ///3
        ///3
        ///8
        ///3
        ///8
        ///5
        ///7
        ///6
        ///3
        ///10
        ///3
        ///5
        ///7
        ///12
        ///7
        ///8
        ///9
        ///12
        ///5
        ///7
        ///6
        ///9
        ///10
        ///7
        ///5
        ///10
        ///5
        ///6
        ///6
        ///10
        ///6
        ///8
        ///3
        ///3
        ///7
        ///7
        ///5
        ///3
        ///8
        ///7
        ///7
        ///2
        ///12
        ///8
        ///5
        ///5
        ///5
        ///6
        ///7
        ///9
        ///12
        ///6
        ///10
        ///3
        ///12
        ///5
        ///3
        ///12
        ///9
        ///5
        ///10
        ///10
        ///12
        ///6
        ///3
        ///5
        ///9
        ///5
        ///7
        ///6
        ///8
        ///10
        ///7
        ///3
        ///6
        ///12
        ///5
        ///6
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testLabelReal {
            get {
                return ResourceManager.GetString("testLabelReal", resourceCulture);
            }
        }
    }
}
